version: '3'
services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=Japan
    volumes:
      - db_data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: ./docker/Ruby/Dockerfile
    tty: true
    stdin_open: true
    # command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bin/rails s -p 3000 -b 0.0.0.0"
    # command: /bin/sh -c "rm -f ./tmp/pids/server.pid && bin/rails s -p 3000 -b 0.0.0.0 -e production"
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myapp:cached
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: ./docker/Nginx/Dockerfile
    volumes:
      - .:/myapp:cached
      - ./nginx/log:/var/log/nginx/
      - ./ssl:/etc/nginx/cert/
    ports:
      - 80:80
    depends_on:
      - web

  webpack:
    build:
      context: .
      dockerfile: ./docker/Node/Dockerfile
    tty: true
    stdin_open: true
    command: npm run watch
    volumes:
      - .:/myapp:cached
    ports:
      - 8891:8891
    depends_on:
      - nginx

volumes:
  public-data:
  tmp-data:
  log-data:
  db_data:
    driver: local
