version: '3'
services:
  python:
    restart: always
    build: .
    command: sh -c "python3 manage.py runserver 0.0.0.0:8000"
    container_name: 'python'
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
